#!/bin/bash

set -e

WORKSPACE=/var/lib/go-agent/pipelines/mydockerjava
REGISTRY_URL=10.112.4.102:5000
cp /opt/apache-maven-3.5.0-bin.tar.gz $WORKSPACE/maven
#docker images | grep none | awk '{print $3}'| xargs docker rmi -f
sudo docker build -t oce/maven:3.5.0 $WORKSPACE/maven
if sudo docker ps -a | grep -i maven; then
   sudo docker rm -f maven
fi
sudo docker create --name maven oce/maven:3.5.0
sudo docker cp maven:/hello/target/hello.war $WORKSPACE/hello
sudo docker build -t $REGISTRY_URL/oce/hello:1.0 $WORKSPACE/hello
sudo docker push $REGISTRY_URL/oce/hello:1.0
if sudo docker ps -a | grep -i newhello;then
   sudo docker rm -f newhello
fi
sudo docker run -d -p 80:8080 --name newhello --link oceoracle:linksql $REGISTRY_URL/oce/hello:1.0


if sudo docker images |grep none ; then
   sudo docker images |grep none |awk '{print $3}' | sudo xargs docker rmi -f
fi





exec "$@"
