#!/bin/bash

set -e

WORKSPACE=/var/lib/go-agent/pipelines/jerry
REGISTRY_URL=10.112.4.102:5000
#cp /opt/apache-maven-3.5.0-bin.tar.gz $WORKSPACE/maven
#docker images | grep none | awk '{print $3}'| xargs docker rmi -f
sudo docker build -t bj/maven:3.5.0 $WORKSPACE/maven
#if sudo docker ps -a | grep -i maven; then
#   sudo docker rm -f maven
#fi
#sudo docker create --name maven bj/maven:3.5.0
if sudo docker ps -a | grep -i maven; then
   sudo docker exec -it /bin/bash /opt/test.sh  > /dev/null 2>&1
else
   sudo docker run -d -p 2212:22  --name maven bj/maven:3.5.0
fi
#sudo docker create --name maven bj/maven:3.5.0
#sudo docker run -d -p 2212:22  --name maven bj/maven:3.5.0
#sudo docker cp maven:/hello/target/hello.war $WORKSPACE/hello
#sudo docker build -t $REGISTRY_URL/bj/hello:1.0 $WORKSPACE/hello
#sudo docker push $REGISTRY_URL/bj/hello:1.0
#if sudo docker ps -a | grep -i hello;then
#   sudo docker rm -f hello
#fi
#sudo docker run -d -p 80:8080 --name hello --link oceoracle:linksql $REGISTRY_URL/bj/hello:1.0


if sudo docker images |grep none ; then
   sudo docker images |grep none |awk '{print $3}' | sudo xargs docker rmi -f
fi





exec "$@"
