#
# MAINTAINER        Jerry Xiao <ocellus@163.com>
# DOCKER-VERSION    1.6.2
#
# Dockerizing HelloWorld: Dockerfile for building HelloWorld images
#
FROM       bj/tomcat:7.0.55
MAINTAINER Jerry Xiao <ocellus@163.com>

#ADD init /init
#
#ENTRYPOINT ["/init", "/scripts/run"]
